sns/accounts/urls.py
from django.urls import path
from .views import (
   RegistUserView,HomeView, 
   UserLoginView, UserLogoutView, #追加
   ProfileEditView,UserListView, # 追加
)
app_name = 'accounts'
urlpatterns = [
   path('home/', HomeView.as_view(), name='home'),
   path('regist/', RegistUserView.as_view(), name='regist'),
   path('login/', UserLoginView.as_view(), name='login'), #追加
   path('logout/', UserLogoutView.as_view(), name='logout'),  #追加 
   path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'), # 追加
   path('userlist/', UserListView.as_view(), name='userlist'), # 追加
]

sns/sns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # mediaを使うために追加
from . import settings  # mediaを使うために追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('microposts/', include('microposts.urls')),
]
# mediaを使うために追加
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sns/accounts/models.py
from django.db import models
from django.contrib.auth.models import (
   BaseUserManager, AbstractBaseUser, PermissionsMixin
)
from django.urls import reverse_lazy

# Create your models here.
class UserManager(BaseUserManager):
   def create_user(self, username, email, password=None):
       if not email:
           raise ValueError('Enter Email') # エラーメッセージ
       user = self.model(
           username=username,
           email=email
       )
       user.set_password(password) # passwordを引数にとってパスワード設定
       user.save(using=self._db) # データベースへユーザーを保存
       return user
   def create_superuser(self, username, email, password):
        """
        Creates and saves a superuser with the given email and password.
        """
        user = self.create_user(
           username,
           email,
           password=password,
        )
        user.staff = True
        user.admin = True
        user.super = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser, PermissionsMixin):
   username = models.CharField(max_length=50, unique=True)
   email = models.EmailField(max_length=50, unique=True)
   is_active = models.BooleanField(default=True)
   is_staff = models.BooleanField(default=False)
   shop_flag = models.BooleanField(default=0)
   shop_url = models.URLField(max_length=200, null=True, blank=True)
   customer_age = models.IntegerField(default=0, null=True, blank=True)
   tel = models.CharField(max_length=11)
   # プロフィール画像をavatarとして設定
   avatar = models.ImageField(blank=True, null=True)  
   EMAIL_FIELD = 'email'
   USERNAME_FIELD = 'username'
   REQUIRED_FIELDS = ['email'] 
   
   objects = UserManager()
   
   def get_absolute_url(self):
       return reverse_lazy('accounts:home')

sns/accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import AuthenticationForm # 追加

class RegistForm(forms.ModelForm):
   username = forms.CharField(label='ユーザーネーム')
   email = forms.EmailField(label='E-mail アドレス')
   password = forms.CharField(label='パスワード', widget=forms.PasswordInput())
   class Meta:
       model = User
       fields = ['username', 'email', 'password']
   def save(self, commit=False):
       user = super().save(commit=False)
       #validate_password(self.cleaned_data['password'], user)
       user.set_password(self.cleaned_data['password'])
       user.save()
       return user

class LoginForm(AuthenticationForm):  # 追加
   username = forms.CharField(label='ユーザーネーム') 
   password = forms.CharField(label='パスワード', widget=forms.PasswordInput) 

class ProfileForm(forms.ModelForm):
   def __init__(self, *args, **kwargs):
       super(ProfileForm, self).__init__(*args, **kwargs)
       
       for field in self.fields.values():  # bootstrapで使用するform-controlクラス
           field.widget.attrs['class'] = 'form-control'
           
   class Meta:
       model = User
       fields = ('username', 'email', 'avatar')
       help_texts = {
           'username': None,
           'email':None,
       }
       

sns/accounts/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView 
from django.views.generic.base import TemplateView
from .forms import RegistForm, LoginForm, ProfileForm 
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import ListView 
from django.contrib.auth.mixins import LoginRequiredMixin 
from .models import User # 追加
class HomeView(TemplateView):
   template_name = 'accounts/home.html'
class RegistUserView(CreateView):
   template_name = 'accounts/regist.html'
   form_class = RegistForm
class UserLoginView(LoginView):  
   template_name = 'accounts/login.html'
   authentication_form = LoginForm
class UserLogoutView(LogoutView): 
   pass
class ProfileEditView(LoginRequiredMixin, UpdateView): 
   template_name = 'accounts/edit_profile.html'
   model = User
   form_class = ProfileForm
   success_url = '/accounts/edit_profile/'
   def get_object(self):
       return self.request.user

class UserListView(LoginRequiredMixin, ListView): # 追加
   template_name = 'accounts/userlist.html'
   model = User
   def get_queryset(self):
       print(User.objects.all())  # 追加
       return User.objects.all()

sns/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block content %}
   <div class="content-wrapper">
       <div class="container-fluid">
           <div class="row">
               <div class="col-sm-6 offset-sm-3">
                   <div class="card">
                       <div class="card-header">
                           <h4><b>プロフィール更新</b></h4>
                       </div>
                       <div class="card-body">
                           {# 画像ファイルをアップロードするためenctype="multipart/form-data"を指定#}
                           <form action="{% url 'accounts:edit_profile' %}" method="post" 
                               enctype="multipart/form-data">
                               {% csrf_token %}
                               {% bootstrap_form form %}
                               <button class='btn btn-outline-success btn-block' type="submit">更新</button>
                           </form>
                       </div>
                   </div>
               </div>
           </div>
       </div>
   </div>
{% endblock %}

sns/templates/accounts/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
   <div class="center jumbotron">
       <div class="text-center">
           <h1>Welcome to the Microposts</h1>
           <a class="btn btn-outline-secondary btn-sm"
                          href="{% url 'accounts:regist' %}"
                          role="button">Sign in Now!</a>
       </div>
   </div>
{% endblock %}

sns/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
   <div class="row">
       <div class="col-sm-6 offset-sm-3">
           <h1 >ログイン</h1> <!--変更-->
           <form method="POST">
               {% csrf_token %}
               {% bootstrap_form form %}             
               <button type="submit" class="btn btn-primary" name="button">
                   ログイン <!--変更-->
               </button> 
           </form>
       </div>
   </div>
{% endblock %}

sns/templates/accounts/regist.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
   <div class="row">
       <div class="col-sm-6 offset-sm-3">
           <h1>ユーザー登録</h1>
           <form method="post">
               {% csrf_token %}
               {% bootstrap_form form %}
               <button type="submit" class="btn btn-primary" name="button">
                   ユーザー登録
               </button>
           </form>
       </div>
   </div>
{% endblock %}

sns/templates/accounts/userlist.html
{% extends 'base.html' %}
{% block content %}
   <div class="content-wrapper">
       <div class="container-fluid">
           <!--ページタイトル-->
           <div class="card mb-3">
               <div class="card-header">
                   <h4><b> ユーザー 一覧</b></h4>
               </div>
               <div class="card-body">
                   <!-- テーブル表の定義 -->
                   <div class="table table-responsive">
                       <table id='user_list' width="100%" class="table table-striped table-bordered table-hover">
                           <!-- 表の列の定義-->
                           <thead>
                           <tr>
                               <th class="text-center">ユーザー</th>
                               <th class="text-center">画像</th>
                           </tr>
                           </thead>
                           <!-- ここまでが表の列の定義-->
                           <!-- 表のデータ部分の表示-->
                           <tbody>
                           {# デフォルトはobject_listとなるが、view.pyでcontextとして指定することも出来る#}
                           {% for item in object_list %}
                               <tr class="odd gradeX text-center">
                                   <td class="text-center" style="width: 50%">{{ item.username }}</td>
                                   <td class="text-center" style="width: 50%">
                               {# ユーザーがプロフィール画像を持っている場合#}
                               {% if item.avatar %}
                                   <img class="rounded img-fluid mx-auto d-block" src="{{ item.avatar.url }}"
                                    id="avatar-thumbnail" alt="avatar_thumbnail">
                               {# ユーザーがプロフィール画像を持ってない場合は”avatar_thumbnailを表示 #}
                               {% else %}
                                   <img class="rounded img-fluid mx-auto d-block" alt="avatar_thumbnail">
                               {% endif %}</td>
                               </tr>
                           {% endfor %}
                           </tbody>
                            <!-- ここまでが表のデータ部分の表示-->
                       </table>
                       <!-- ここまでがテーブル表の定義 -->
                   </div>
               </div>
           </div>
       </div>
   </div>
{% endblock %}