sns/accounts/urls.py
from django.urls import path
from .views import (
   RegistUserView,HomeView, 
   UserLoginView, UserLogoutView, #追加
   ProfileEditView,UserListView, # 追加
)
app_name = 'accounts'
urlpatterns = [
   path('home/', HomeView.as_view(), name='home'),
   path('regist/', RegistUserView.as_view(), name='regist'),
   path('login/', UserLoginView.as_view(), name='login'), #追加
   path('logout/', UserLogoutView.as_view(), name='logout'),  #追加 
   path('edit_profile/', ProfileEditView.as_view(), name='edit_profile'), # 追加
   path('userlist/', UserListView.as_view(), name='userlist'), # 追加
]

sns/sns/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static  # mediaを使うために追加
from . import settings  # mediaを使うために追加

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('microposts/', include('microposts.urls')),
]
# mediaを使うために追加
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sns/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <title>Microposts</title>
   {# bootstrapのCSS、自作のCSSを読み込む#}
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
   integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'accounts/style.css' %}">
   {% load bootstrap4 %}
</head>
<body>
<header class="mb-4">
   <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
       <a class="navbar-brand" href="#">Microposts</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
           <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav navbar-left">{% if user.is_authenticated %}
               <li class="nav-item">
                   <a class="nav-link" href="＃">All Posts</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="＃">All Users</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="＃">New post</a>
               </li>
               <li class="nav-item dropdown">
                   <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" 
                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                       {{ user.username }}'s detail
                   </a>
                   <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                       <a class="dropdown-item" href="＃">My posts</a>
                       <a class="dropdown-item" href="＃">Following</a>
                       <a class="dropdown-item" href="＃">Follower</a>
                   </div>
               </li>{% endif %}
           </ul>
           <ul class="navbar-nav navbar-right">{% if user.is_authenticated %}
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
               </li>{% else %}
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'accounts:regist' %}">Sign in</a>
               </li>{% endif %}
           </ul>
       </div>
   </nav>
</header>
{% block content %}
<!-- ここに各htmlの内容が反映される -->
{% endblock content %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS,Fontawasome -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
       integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
       crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
       integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
       crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
       integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
       crossorigin="anonymous"></script>
<script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>

{% block footer %}
{% endblock footer %}
</body>
</html>